"""Deterministic project-status snapshot (P3).

The snapshot is generated from live source registries - CLI commands,
built-in checks, public contracts, MCP tools, knowledge packs, and the
Loop Factory queue - never from hand-written prose. ``project status
--check`` regenerates the markdown and diffs it against the committed
``docs/project-status.md`` so documentation drift fails in CI.

Everything is sorted and timestamp-free: identical registries produce
byte-identical output on any machine.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from forge_doctor_data.version import VERSION

GENERATED_HEADER = (
    "<!-- Generated by `forge-doctor-data project status --write` - "
    "do not edit by hand; CI diffs this file against the live registries. -->"
)
STATUS_DOC = Path("docs") / "project-status.md"


def _iter_commands(app: Any, prefix: str = "") -> list[str]:
    """Full command paths (``project status``) from a Typer app, recursively."""
    names: list[str] = []
    for info in app.registered_commands:
        name = info.name or info.callback.__name__.replace("_", "-")
        names.append(prefix + name)
    for group in app.registered_groups:
        sub = group.typer_instance
        if sub is not None:
            names.extend(_iter_commands(sub, prefix + group.name + " "))
    return names


def _repo_root() -> Path:
    """Best-effort repo root: works for editable checkouts and installed wheels."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").is_file() and (parent / "src").is_dir():
            return parent
    return Path.cwd()


def _factory_counts(root: Path) -> dict[str, int]:
    specs = root / "factory" / "specs"
    counts = {stage: 0 for stage in ("inbox", "active", "archive")}
    for stage in counts:
        d = specs / stage
        if d.is_dir():
            counts[stage] = sum(1 for p in d.glob("*.md"))
    runs = root / "factory" / "runs"
    counts["runs"] = sum(1 for p in runs.rglob("*.md")) if runs.is_dir() else 0
    return counts


def collect_status(root: Path | None = None) -> dict[str, Any]:
    """One deterministic snapshot across every public registry."""
    from forge_doctor_data.cli.app import app
    from forge_doctor_data.core.knowledge import list_packs
    from forge_doctor_data.core.schemas import SCHEMAS
    from forge_doctor_data.core.service import ScanService
    from forge_doctor_data.integrations.mcp_server import _TOOL_DEFS
    from forge_doctor_data.plugins.discovery import discover_plugins

    root = root or _repo_root()
    registry, _ = ScanService().build_registry(no_plugins=True)

    categories: dict[str, list[str]] = {}
    for check in registry.all():
        categories.setdefault(check.category, []).append(check.id)

    domains = sorted({domain for domain, _name, _pack in list_packs()})
    plugins = sorted(
        {p.distribution or p.name for p in discover_plugins() if (p.distribution or p.name)}
    )
    return {
        "version": VERSION,
        "commands": sorted(_iter_commands(app)),
        "checks": {cat: sorted(ids) for cat, ids in sorted(categories.items())},
        "check_total": len(registry.all()),
        "contracts": sorted(SCHEMAS),
        "mcp_tools": sorted(t["name"] for t in _TOOL_DEFS),
        "knowledge_domains": domains,
        "plugins": plugins,
        "factory": _factory_counts(root),
    }


def render_status_markdown(status: dict[str, Any]) -> str:
    """The committed artifact checked by ``--check``."""
    lines = [
        "# Project Status",
        "",
        GENERATED_HEADER,
        "",
        f"Package version: `{status['version']}`",
        "",
        "## Surface",
        "",
        f"- CLI commands: {len(status['commands'])}",
        f"- Built-in checks: {status['check_total']} across {len(status['checks'])} categories",
        f"- Contracts: {len(status['contracts'])}",
        f"- MCP tools: {len(status['mcp_tools'])}",
        f"- Knowledge domains: {len(status['knowledge_domains'])}",
        f"- Plugins discovered: {len(status['plugins'])}",
        "",
        "## Commands",
        "",
        *(f"- `{c}`" for c in status["commands"]),
        "",
        "## Checks by category",
        "",
    ]
    for cat, ids in status["checks"].items():
        lines.append(f"- **{cat}** ({len(ids)}): {', '.join(ids)}")
    lines += [
        "",
        "## Contracts",
        "",
        *(f"- `{c}`" for c in status["contracts"]),
        "",
        "## MCP tools",
        "",
        *(f"- `{t}`" for t in status["mcp_tools"]),
        "",
        "## Knowledge domains",
        "",
        *(f"- `{d}`" for d in status["knowledge_domains"]),
        "",
        "## Plugins",
        "",
    ]
    lines += [f"- `{p}`" for p in status["plugins"]] if status["plugins"] else ["_none installed_"]
    factory = status["factory"]
    lines += [
        "",
        "## Loop Factory",
        "",
        f"- inbox: {factory['inbox']}",
        f"- active: {factory['active']}",
        f"- archive: {factory['archive']}",
        f"- run records: {factory['runs']}",
        "",
    ]
    return "\n".join(lines)


def render_status_text(status: dict[str, Any]) -> str:
    """Compact human-readable summary for the terminal."""
    factory = status["factory"]
    return "\n".join(
        [
            f"forge-doctor-data {status['version']}",
            f"commands: {len(status['commands'])}",
            f"checks: {status['check_total']} ({len(status['checks'])} categories)",
            f"contracts: {len(status['contracts'])}",
            f"mcp tools: {len(status['mcp_tools'])}",
            f"knowledge domains: {len(status['knowledge_domains'])}",
            f"plugins: {len(status['plugins'])}",
            "factory: "
            f"{factory['inbox']} inbox / {factory['active']} active / "
            f"{factory['archive']} archive / {factory['runs']} runs",
        ]
    )


def status_json(status: dict[str, Any]) -> str:
    return json.dumps(status, indent=2, sort_keys=True, ensure_ascii=False)


def status_doc_path(root: Path | None = None) -> Path:
    return (root or _repo_root()) / STATUS_DOC


def check_status_doc(root: Path | None = None) -> list[str]:
    """Diff committed ``docs/project-status.md`` against the regenrated one.

    Returns mismatch lines; empty list means the doc is current. A missing
    file reports a single "run --write" hint instead of a full diff dump.
    """
    root = root or _repo_root()
    path = root / STATUS_DOC
    fresh = render_status_markdown(collect_status(root))
    if not path.is_file():
        return [
            f"{STATUS_DOC} is missing - regenerate with `forge-doctor-data project status --write`."
        ]
    current_text = path.read_text(encoding="utf-8")
    if current_text == fresh + "\n":
        return []
    current = current_text.splitlines()
    fresh_lines = (fresh + "\n").splitlines()
    import difflib

    return list(
        difflib.unified_diff(
            current, fresh_lines, fromfile=str(STATUS_DOC), tofile="regenerated", lineterm=""
        )
    )
